"""

--- Day 22: Monkey Market ---

As you're all teleported deep into the jungle, a monkey steals The Historians' device! You'll need get it back while The Historians are looking for the Chief.

The monkey that stole the device seems willing to trade it, but only in exchange for an absurd number of bananas. Your only option is to buy bananas on the Monkey Exchange Market.

You aren't sure how the Monkey Exchange Market works, but one of The Historians senses trouble and comes over to help. Apparently, they've been studying these monkeys for a while and have deciphered their secrets.

Today, the Market is full of monkeys buying good hiding spots. Fortunately, because of the time you recently spent in this jungle, you know lots of good hiding spots you can sell! If you sell enough hiding spots, you should be able to get enough bananas to buy the device back.

On the Market, the buyers seem to use random prices, but their prices are actually only pseudorandom! If you know the secret of how they pick their prices, you can wait for the perfect time to sell.

The part about secrets is literal, the Historian explains. Each buyer produces a pseudorandom sequence of secret numbers where each secret is derived from the previous.

In particular, each buyer's secret number evolves into the next secret number in the sequence via the following process:

Calculate the result of multiplying the secret number by 64. Then, mix this result into the secret number. Finally, prune the secret number.
Calculate the result of dividing the secret number by 32. Round the result down to the nearest integer. Then, mix this result into the secret number. Finally, prune the secret number.
Calculate the result of multiplying the secret number by 2048. Then, mix this result into the secret number. Finally, prune the secret number.
Each step of the above process involves mixing and pruning:

To mix a value into the secret number, calculate the bitwise XOR of the given value and the secret number. Then, the secret number becomes the result of that operation. (If the secret number is 42 and you were to mix 15 into the secret number, the secret number would become 37.)
To prune the secret number, calculate the value of the secret number modulo 16777216. Then, the secret number becomes the result of that operation. (If the secret number is 100000000 and you were to prune the secret number, the secret number would become 16113920.)
After this process completes, the buyer is left with the next secret number in the sequence. The buyer can repeat this process as many times as necessary to produce more secret numbers.

So, if a buyer had a secret number of 123, that buyer's next ten secret numbers would be:

15887950
16495136
527345
704524
1553684
12683156
11100544
12249484
7753432
5908254
Each buyer uses their own secret number when choosing their price, so it's important to be able to predict the sequence of secret numbers for each buyer. Fortunately, the Historian's research has uncovered the initial secret number of each buyer (your puzzle input). For example:

1
10
100
2024
This list describes the initial secret number of four different secret-hiding-spot-buyers on the Monkey Exchange Market. If you can simulate secret numbers from each buyer, you'll be able to predict all of their future prices.

In a single day, buyers each have time to generate 2000 new secret numbers. In this example, for each buyer, their initial secret number and the 2000th new secret number they would generate are:

1: 8685429
10: 4700978
100: 15273692
2024: 8667524
Adding up the 2000th new secret number for each buyer produces 37327623.

For each buyer, simulate the creation of 2000 new secret numbers. What is the sum of the 2000th secret number generated by each buyer?


--- Part Two ---

Of course, the secret numbers aren't the prices each buyer is offering! That would be ridiculous. Instead, the prices the buyer offers are just the ones digit of each of their secret numbers.

So, if a buyer starts with a secret number of 123, that buyer's first ten prices would be:

3 (from 123)
0 (from 15887950)
6 (from 16495136)
5 (etc.)
4
4
6
4
4
2
This price is the number of bananas that buyer is offering in exchange for your information about a new hiding spot. However, you still don't speak monkey, so you can't negotiate with the buyers directly. The Historian speaks a little, but not enough to negotiate; instead, he can ask another monkey to negotiate on your behalf.

Unfortunately, the monkey only knows how to decide when to sell by looking at the changes in price. Specifically, the monkey will only look for a specific sequence of four consecutive changes in price, then immediately sell when it sees that sequence.

So, if a buyer starts with a secret number of 123, that buyer's first ten secret numbers, prices, and the associated changes would be:

     123: 3 
15887950: 0 (-3)
16495136: 6 (6)
  527345: 5 (-1)
  704524: 4 (-1)
 1553684: 4 (0)
12683156: 6 (2)
11100544: 4 (-2)
12249484: 4 (0)
 7753432: 2 (-2)
Note that the first price has no associated change because there was no previous price to compare it with.

In this short example, within just these first few prices, the highest price will be 6, so it would be nice to give the monkey instructions that would make it sell at that time. The first 6 occurs after only two changes, so there's no way to instruct the monkey to sell then, but the second 6 occurs after the changes -1,-1,0,2. So, if you gave the monkey that sequence of changes, it would wait until the first time it sees that sequence and then immediately sell your hiding spot information at the current price, winning you 6 bananas.

Each buyer only wants to buy one hiding spot, so after the hiding spot is sold, the monkey will move on to the next buyer. If the monkey never hears that sequence of price changes from a buyer, the monkey will never sell, and will instead just move on to the next buyer.

Worse, you can only give the monkey a single sequence of four price changes to look for. You can't change the sequence between buyers.

You're going to need as many bananas as possible, so you'll need to determine which sequence of four price changes will cause the monkey to get you the most bananas overall. Each buyer is going to generate 2000 secret numbers after their initial secret number, so, for each buyer, you'll have 2000 price changes in which your sequence can occur.

Suppose the initial secret number of each buyer is:

1
2
3
2024
There are many sequences of four price changes you could tell the monkey, but for these four buyers, the sequence that will get you the most bananas is -2,1,-1,3. Using that sequence, the monkey will make the following sales:

For the buyer with an initial secret number of 1, changes -2,1,-1,3 first occur when the price is 7.
For the buyer with initial secret 2, changes -2,1,-1,3 first occur when the price is 7.
For the buyer with initial secret 3, the change sequence -2,1,-1,3 does not occur in the first 2000 changes.
For the buyer starting with 2024, changes -2,1,-1,3 first occur when the price is 9.
So, by asking the monkey to sell the first time each buyer's prices go down 2, then up 1, then down 1, then up 3, you would get 23 (7 + 7 + 9) bananas!

Figure out the best sequence to tell the monkey so that by looking for that same sequence of changes in every buyer's future prices, you get the most bananas in total. What is the most bananas you can get?

"""

# LIBRARIES
import time
import pathlib
import os
from math import *
from functools import *
from sys import *
from collections import *
from queue import *

# MODULES
from _test import test

# OPTIONAL VARIABLES
DISPLAY_EXTRA_INFO = True
# DISPLAY_EXTRA_INFO = False

def simulate_and_analyze_data_from_hashing_sequence(part, input_str, DEBUG = False, *args):

  # PARSE INPUT DATA

  INITIAL_NUMS = [ int(n) for n in input_str.split('\n') ]


  # CONSTANTS

  NUM_ITERATIONS = 2000


  # UTILITY

  def mix(n, mix_with):
    return n ^ mix_with
  
  def prune(n):
    return n % 16777216

  get_next_n_MEMO = {}
  def get_next_n(n):
    initial_n = n
    if initial_n not in get_next_n_MEMO:

      # Step 1
      mix_with = n * 64
      n = mix(n, mix_with)
      n = prune(n)

      # Step 2
      mix_with = floor(n / 32)
      n = mix(n, mix_with)
      n = prune(n)

      # Step 3
      mix_with = n * 2048
      n = mix(n, mix_with)
      n = prune(n)

      get_next_n_MEMO[initial_n] = n
    return get_next_n_MEMO[initial_n]


  # DATA STRUCTURES

  BUYER_DATA = []                                                             # each element pertains to a buyer and is a list of data
                                                                              # each inner element is a data dictionary pertaining to that iteration


  # ANALYZE

  if not DEBUG: print('RUNNING REAL BUYER_DATA ANALYSIS (PLEASE WAIT)...')

  TIME_AT_START = time.time()

  part_1_total = 0                                                            # PART 1 ONLY

  for INITIAL_NUM in INITIAL_NUMS:
    data = [                                                                  # init data list
      {
        'number': INITIAL_NUM,
        'price': INITIAL_NUM % 10,                                            # % 10 to get the ones digit
        'change': None                                                        # no change data only for first data dictionary
      }
    ]

    n = INITIAL_NUM
    for _ in range(NUM_ITERATIONS):
      n = get_next_n(n)
      data.append({
        'number': n,
        'price': n % 10,
        'change': (n % 10) - data[-1]['price'],
      })
    BUYER_DATA.append(data)

    part_1_total += n                                                         # PART 1 ONLY
  

  if part == 1:                                                               # PART 1: SIMPLY RETURN THE SUM OF THE FINAL SECRET NUMBERS

    if not DEBUG: print(f"(RUN TOOK {(time.time() - TIME_AT_START)} SECS)")   # ~2.26 seconds
    return part_1_total

  else:                                                                       # PART 2: FIND THE MAX REVENUE YOU CAN MAKE FOR A SEQUENCE OF
                                                                              # 4 CHANGE VALUES YOU CHOOSE, SUCH THAT EACH BUYER WILL PAY YOU
                                                                              # THEIR PRICE ON THE LAST OF 4 DAYS FOR THE FIRST OCCURRENCE OF
                                                                              # SUCH A CHANGE SEQUENCE IN THEIR DATA (OR 0 IF IT NEVER HAPPENS)

    POSSIBLE_SEQUENCES = {}                                                   # calculate the revenue resulting from every possible sequence
                                                                              # *as we discover the sequences*
    for buyer_idx in range(len(BUYER_DATA)):
      data = BUYER_DATA[buyer_idx]
      for i in range(1, 2001 - 4 + 1):                                        # data list is 2001 elements long (indices 0-2000)
                                                                              # the first position is after index 0 (no change data at 0)
                                                                              # the last position is index values 1997, 1998, 1999, 2000
        sequence = (
          data[i]['change'],
          data[i + 1]['change'],
          data[i + 2]['change'],
          data[i + 3]['change']
        )
        if sequence not in POSSIBLE_SEQUENCES:                                # init if necessary
          POSSIBLE_SEQUENCES[sequence] = [None] * len(BUYER_DATA)
        if POSSIBLE_SEQUENCES[sequence][buyer_idx] == None:                   # NOTE: ONLY SIMULATE PURCHASE AT FIRST OCCURRENCE OF SEQUENCE!
          POSSIBLE_SEQUENCES[sequence][buyer_idx] = data[i + 3]['price']

    best_revenue = 0
    for revenue_data in POSSIBLE_SEQUENCES.values():                          # find the best revenue among all existing sequences
      revenue = sum([ (0 if r == None else r) for r in revenue_data ])
      best_revenue = max(best_revenue, revenue)

    if not DEBUG: print(f"(RUN TOOK {(time.time() - TIME_AT_START)} SECS)")   # ~6.10 seconds
    return best_revenue


# TEST CASES

test_num = [1]
test_input = None
test_expected = None
func = simulate_and_analyze_data_from_hashing_sequence
skipped_tests = set([ 2, 3, 4 ])
skipped_tests = set([ 3, 4 ])
skipped_tests = set([ 4 ])
skipped_tests = set([  ])
lowest_test = 0
highest_test = 0

FILENAME = pathlib.Path(__file__).name
FILENAME_SPLIT = FILENAME.split('.py')[0].split('day')
DAY_NUM = FILENAME_SPLIT[1] if len(FILENAME_SPLIT) > 1 else None
CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
INPUT_PATH = CURRENT_DIR + '\\' + (f"day{str(DAY_NUM).zfill(2)}-input.txt" if DAY_NUM else 'template-input.txt')
actual_input = open(INPUT_PATH, 'r').read()

sample_input = """1
10
100
2024"""

sample_input2 = """1
2
3
2024"""

# Test case 1
test_input = {
  'part': 1,
  'input_str': sample_input,
  'DEBUG': True,
}
test_expected = 37327623
test(func, test_input, test_expected, test_num, skipped_tests, lowest_test, highest_test)

# Test case 2
test_input = {
  'part': 1,
  'input_str': actual_input,
  'DEBUG': False,
}
test_expected = 13764677935
test(func, test_input, test_expected, test_num, skipped_tests, lowest_test, highest_test)

# Test case 3
test_input = {
  'part': 2,
  'input_str': sample_input2,
  'DEBUG': True,
}
test_expected = 23
test(func, test_input, test_expected, test_num, skipped_tests, lowest_test, highest_test)

# Test case 4
test_input = {
  'part': 2,
  'input_str': actual_input,
  'DEBUG': False,
}
test_expected = 1619
test(func, test_input, test_expected, test_num, skipped_tests, lowest_test, highest_test)